baseurl: ""

profile:
  name: David Charte
  alias: "David C"
  pic: https://secure.gravatar.com/avatar/7083d161b041964b75c38376d9dee37a?s=200
  description: >
    I'm David Charte. I code and do maths. 

  about: >
    I studied a Double Degree on Computer Science and Mathematics.
    Currently I'm doing research and software development in the field of
    [Unsupervised Deep Learning](/blog/2016/09/01/deep-learning/) at the University of Granada. I also contribute
    talks and posts to [LibreIM](https://libreim.github.io).

  links:
    "Academic profile":
      url: https://www.researchgate.net/profile/David_Charte
      icon: graduation-cap
    "Professional profile":
      url: https://linkedin.com/in/fdavidcl
      icon: linkedin-square
    "Projects":
      url: https://github.com/fdavidcl
      icon: github
    "Toots":
      url: https://mstdn.io/@fdavidcl
      icon: mastodon
    "Photos":
      url: https://photos.quotient.space/
      icon: instagram
    "Questions and answers":
      url: http://david.quotient.space/ask
      icon: question-circle
    "Download my CV":
      url: cv.pdf
      icon: file-o
    "fdavidcl [at] ugr [dot] es":
      icon: envelope-o

style:
  background: "ffffff"
  foreground: "2e3440"
  accent: "00626e"
  font: "Source Sans Pro"
  monofont: "Inconsolata"

# This list helps the index page show the correct collections in the desired order
featured:
  tags:
    - research
    - projects

# Settings for the blog section
plugins:
  - octopress-paginate
  - jemoji
#  - jekyll-minifier

exclude:
  - Gemfile
  - vendor

defaults:
  - values:
      lang: es
      layout: post

permalink: pretty

markdown: kramdown
kramdown:
  parse_span_html: false
highlighter: rouge

tag_dir: "/tag"
tag_title_prefix: "Tag '"
tag_title_suffix: "'"
